name: Console CensorChecker
description: Batch tcping probe & Censor checker
author: Space Time
branding:
  icon: eye
  color: orange

inputs:
  TARGETS:
    description: One target per line to check or a single file path containing targets
  BROWSER:
    description: "Chromium browser path (Default: google-chrome)"
    default: google-chrome
  PORT:
    description: "Port for unspecified targets (Default: 443)"
    default: 443

outputs:
  RESULTS:
    value: ${{ steps.check-censor.outputs.RESULTS }}
    description: "JSON result of target avg latency ms (Censored: 2147483647)"

runs:
  using: composite
  steps:
    - name: Check Censor
      id: check-censor
      shell: pwsh
      env:
        TARGETS: ${{ inputs.TARGETS }}
        BROWSER: ${{ inputs.BROWSER }}
        PORT: ${{ inputs.PORT }}
      run: |
        using namespace System.Collections.Specialized

        [string] $targetPath = Join-Path $env:GITHUB_ACTION_PATH "Target.txt"
        [string] $externalTargetPath = Join-Path $env:GITHUB_WORKSPACE "Target.txt"

        if (-not [string]::IsNullOrWhiteSpace($env:TARGETS)) {
            [string[]] $targets = @(($env:TARGETS -split "\r?\n").Trim() -ne "")

            if ($targets.Count -eq 1 -and (Test-Path -LiteralPath $targets[0] -PathType Leaf)) {
                Copy-Item -LiteralPath $targets[0] $targetPath -Force
            }
            else {
                Set-Content -LiteralPath $targetPath $targets
            }
        }
        elseif ((Test-Path -LiteralPath $externalTargetPath -PathType Leaf) -and $externalTargetPath -ne $targetPath) {
            Copy-Item -LiteralPath $externalTargetPath $targetPath -Force
        }
        elseif (-not (Test-Path -LiteralPath $targetPath -PathType Leaf)) {
            throw "提供 TARGETS 参数或 Target.txt 文件"
        }

        . (Join-Path $env:GITHUB_ACTION_PATH "App.ps1")

        [OrderedDictionary] $results = [ordered]@{}

        [App]::new().Main($env:BROWSER, $env:PORT, {
            param([PSCustomObject] $result)

            [App]::WriteCheckResult($result)
            $results[$result.Target] = $result.Latency
        })

        Add-Content -LiteralPath $env:GITHUB_OUTPUT "RESULTS=$(ConvertTo-Json $results -Compress)"
